#ifndef CPP3_3_SMARTCALC_V2_0_1_SRC_CALCULATOR_CALCULATOR_VIEW_CALCULATOR_HEADERS_MAIN_VIEW_H_
#define CPP3_3_SMARTCALC_V2_0_1_SRC_CALCULATOR_CALCULATOR_VIEW_CALCULATOR_HEADERS_MAIN_VIEW_H_

#include "calculator-view.h"
#include "credit-view.h"

QT_BEGIN_NAMESPACE
namespace Ui {
class CalculationView;
class CreditView;
};  // namespace Ui
QT_END_NAMESPACE

#endif  // CPP3_3_SMARTCALC_V2_0_1_SRC_CALCULATOR_CALCULATOR_VIEW_CALCULATOR_HEADERS_MAIN_VIEW_H_
