check:
	clang-format -style=Google -i Calculator/common/model/calculator/headers/calculator-model.h
	clang-format -style=Google -i Calculator/common/model/calculator/sourses/calculator-model.cc
	clang-format -style=Google -i Calculator/calculator/controller/headers/calculator-controller.h
	clang-format -style=Google -i Calculator/calculator/controller/sourses/calculator-controller.cc